### ISSUE TITLE
No change in screen color

### ISSUE THREAD

**Issue by njhilliard** [xflux-gui/xflux-gui#27]
I'm running Xenial with Gnome desktop. As the title says, when I run either the gui or xflux from command line, there is no change in color. If I run the gui I get some useful messages, however.
Here is my terminal:
```
nate@nate-UX305:~$ fluxgui
/usr/lib/python2.7/dist-packages/fluxgui/fluxapp.py:75: GtkWarning: Cannot transform xsetting Net/IconThemeName of type gchararray to type GdkColor

  gtk.gdk.screen_get_default().get_setting('gtk-icon-theme-name')
/usr/lib/python2.7/dist-packages/fluxgui/fluxapp.py:75: GtkWarning: Cannot transform xsetting Net/IconThemeName of type gchararray to type gint

  gtk.gdk.screen_get_default().get_setting('gtk-icon-theme-name')
```

**Comment by x-ji** [comment]
I also seem to have the same issue. Redshift has also stopped working for me although it was working fine a few weeks ago. Is it due to a change in some upgraded system package?

**Comment by x-ji** [comment]
Turns out it has something to do with the newest kernel 4.4.0-34. Using 4.4.0-31 solved the issue. See https://ubuntuforums.org/showthread.php?t=2333398

**Comment by Alkaris** [comment]
I have similar issue to this and I'm on Linux Mint 18 Cinnamon edition 64-bit

```
$ fluxgui
/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py:75: GtkWarning: Cannot transform xsetting Net/IconThemeName of type gchararray to type GdkColor

  gtk.gdk.screen_get_default().get_setting('gtk-icon-theme-name')
/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py:75: GtkWarning: Cannot transform xsetting Net/IconThemeName of type gchararray to type gint

  gtk.gdk.screen_get_default().get_setting('gtk-icon-theme-name')
Created new window in existing browser session.
^CTraceback (most recent call last):
  File "/usr/local/bin/fluxgui", line 23, in <module>
    subprocess.call([sys.executable, path] + sys.argv[1:])
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py", line 235, in <module>
    app.exit()
  File "/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py", line 46, in exit
    gtk.main_quit()
RuntimeError: called outside of a mainloop
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1392, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

```

**Comment by itsabear** [comment]
Please upgrade your kernel with `sudo apt-get dist-upgrade` to move to lastest kernel available for Ubuntu. If you want to use 4.4.0-31, run this - `sudo apt-get install linux-image-4.4.0-31-generic linux-headers-4.4.0-31`.

**Comment by holocronweaver** [comment]
This issue is still present on the pre-release Ubuntu kernel `4.4.0-38-generic`, which I tried after `4.4.0-36-generic` failed to fix the issue. So currently there appears to be no fix available if you use newer kernels.

**Comment by ntc2** [comment]
People who are having this issue might try RedShift instead. E.g. `redshift -v -t 4500:2500` to set day time color temp to 4500 and night time color temp to 2500. This is what I use on my work laptop, which has a fancy graphics card that is unsupported by Flux.

**Comment by holocronweaver** [comment]
Nice find @ntc2! redshift works on Ubuntu kernel `4.4.0-38-generic` with an Nvidia GTX 970m.

**Comment by ntc2** [comment]
@holocronweaver : haha, small world:
``` shell
$ lspci | grep VGA
01:00.0 VGA compatible controller: NVIDIA Corporation GM204M [GeForce GTX 970M] (rev a1)
```

**Comment by itsabear** [comment]
> People who are having this issue might try RedShift instead. E.g. redshift -v -t 4500:2500 to set day time color temp to 4500 and night time color temp to 2500. @ntc2 

Can I ask, is that also a way to set daytime with bluelight filter, or should I change 4500 value to 2500 too to make daylight filter color same as night?

**Comment by x-ji** [comment]
@itsabearThe easiest way to set the color you want is `redshift -O 2500` for example. -O means "oneshot" and it doesn't differentiate on time.

**Comment by itsabear** [comment]
@x-ji I tried that, and the program returns `using method `\`randr`. The screen goes to that temperate in a splite second, and gone back to normal. How to fix this?

**Comment by x-ji** [comment]
@itsabear That's because you have a previous redshift process running. Close that process first, otherwise it will control the temperature continuously. -O does what it says, it adjusts the temperature at once and doesn't keep a redshift process running, so in your case the previous process overrode this setting.

**Comment by itsabear** [comment]
@x-ji That's worked. Thanks. By killing running fluxgui in the bakground did it. So if anybody else also wanna try redshift, don't forget to kill other process of redshift or fluxgui in the background. You can search for it with `ps aux | grep "fluxgui"` or `ps aux | grep "redshift" and using `killall <process ID>`.

**Comment by mDfRg** [comment]
I also had problem with non-working flux after some Ubuntu 16.04 upgrade. The solution for me was a downgrade of nvidia drivers from version 367.57 to 361.42.

**Comment by synthor** [comment]
Even with the lastest 367.57 it doesn't work. Am on Ubuntu 14.04.5 x64 with 4.4.0-45 kernel. Card is a GT 430.

Will try 361.42 now...

**Comment by synthor** [comment]
Yup, that's also the solution for Ubuntu 14.04.5 (with the HWE stack from 16.04).

**Comment by synthor** [comment]
I also added a comment to the bugreport on launchpad.

**Comment by x-ji** [comment]
@synthor Well no. I reported that it doesn't work on both Nvidia card and the integrated Intel card. While on another kernel it works on both Nvidia and Intel cards. I currently have Nvidia 364 driver and I have redshift working totally fine. So I don't believe it's induced by NVIDIA driver. Maybe you're having another bug?

**Comment by synthor** [comment]
The same bug affects us.

It doesn't seem to be related to the kernel itself, because you with Intel/Nvidia setup, @mDfRg and me have the problem with a Nvidia only setup. There's a little module running inside the kernel which is the graphics driver which contains the bug.

I'm personally affected since I updated the Nvidia driver to a version a few days ago.

On my notebook I use 14.04.5 with 4.4.0-45 aswell with an Intel onboard and an AMD card and the AMD propritary driver. It always worked without problems on this machine and I never upgraded the AMD driver since a while.

Maybe I should... ;)

So, it seems to be related to the graphics drivers. We should contact their vendors with this.

**Comment by synthor** [comment]
Still looking what is causing the bug..

- ps aux'ed the exact xflux command and saved it
- reinstalled the latest Nvidia driver
- no xflux process running after logon
- opened a terminal and ran the saved command

```
--------
Welcome to xflux (f.lux for X)
This will only work if you're running X on console.

Found 1 screen.
Sorry, we only support 8 and 10-bit displays right now.
synthor@ubunthor:~$
```

"This will only work if you're running X on console." is normal says Google.

"Sorry, we only support 8 and 10-bit displays right now." is the culprit. The xflux process exits after that.

Googled the error message gave me this: https://forum.justgetflux.com/topic/2373/sorry-we-only-support-8-and-10-bit-displays-right-now/17

Haven't tested his solution and not read any further yet. That's my latest info.

**Comment by merildev** [comment]
I have a Radeon RX 480 (so no nVidia drivers on my Linux) and I have the exact same issue. Could it be related to the screen resolution? I'm on 2560x1440.
FYI, I use ArchLinux with kernel v4.8.6.

**Comment by synthor** [comment]
Could you open a terminal and post the output of

`/usr/local/bin/xflux -l 50 -k 3400 -nofork`

please?

Which driver do you use? radeon-si?

**Comment by bhlevca** [comment]
Well, I had been watching this bug for a while. It appears that xflux incorrectly detects the display. I have 10 bit display and I am getting the following

> Welcome to xflux (f.lux for X)
> This will only work if you're running X on console.
> 
> Guessing your longitude is -75.0 based on your timezone
> Specify it with -g to make things better.
> Found 1 screen.
> Sorry, we only support 8 and 10-bit displays right now.

**Comment by merildev** [comment]
I use the AMDGPU driver (https://wiki.archlinux.org/index.php/AMDGPU).

When I run the command "xflux -l 50 -k 3400 -nofork", I have the same "Sorry, we only support 8 and 10-bit displays right now." issue.

**Comment by synthor** [comment]
@bhlevca That explains why bending that two assembler jumps into that piece of code with radare didn't helped. Since we only have the binary, that would have been a quick'n'dirty hack.

@merildev Well, yes it does matter. If we would have the sources of xflux we could change it to work again with all cards, displays, compositors, ...

That bug is over eight months old. Don't think they will do something in short time.

**Comment by Zelmor** [comment]
starting fluxgui under i3 doesn't change the monitor temperature. The applet appears in the bottom right corner on my i3-status bar, and can be clicked. However, when clicking **preview**, the window locks up and the button doesn't let go of the mouse focus. All output on terminal is:

```
/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py:86: Warning: /build/glib2.0-94amRy/glib2.0-2.50.1/./gobject/gsignal.c:2523: signal 'child-added' is invalid for instance '0x1a29190' of type 'GtkMenu'
  self.indicator.set_menu(self.create_menu())
```

It was built from the git repository following the instructions. 

**Videocard driver:** 
NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.57  Mon Oct  3 20:37:01 PDT 2016
GCC version:  gcc version 5.4.1 20161019 (Debian 5.4.1-3) 

**Kernel:**
4.7.0-1-amd64 #1 SMP Debian 4.7.8-1 (2016-10-19) x86_64 GNU/Linux

Debian stretch, up to date. My card is a GTX 560. 

**Steps to replicate the issue**

Start fluxgui from terminal.

**Comment by ntc2** [comment]
This seems to be an upstream problem, e.g.  https://forum.justgetflux.com/topic/2373/sorry-we-only-support-8-and-10-bit-displays-right-now/17, and I don't think there's anything we can do in `fluxgui`. So, marking as "won't fix".

**Comment by carlosnewmusic** [comment]
Welcome to xflux (f.lux for X)
This will only work if you're running X on console.

Found 1 screen.
Sorry, we only support 8 and 10-bit displays right now.

debian 9 kernel 4.8.15.2 xorg 1.19.1 XFCE

**Comment by Alkaris** [comment]
What I don't get is why you're not supporting proper native 32-bit displays? I don't think anybody here is still using 8-bit /10-bit displays anymore, its pretty outdated tbh… and most people are running Linux on medium to high-end builds these days complete with dedicated graphics cards that run 32-bit displays. The console screen wouldn't be running 8-bit / 10-bit either since it would follow its native screen size that it detects and is connected to.

**Comment by spokendotcpp** [comment]
Hi, antergos + RX 480, same issue for me.

**Comment by ntc2** [comment]
Looks like we may be able to fix this now by using newer `xflux` binary and passing `-r 0`. See forum thread here: https://forum.justgetflux.com/topic/2373/sorry-we-only-support-8-and-10-bit-displays-right-now.

**Comment by Yahoe001** [comment]
This is now affecting Ubuntu 17.04, used to work up to a couple days ago.

**Comment by pizzadude** [comment]
@Yahoe001 Yeah I noticed that in Ubuntu Mate 17.04. Had to switch to Redshift. It's a shame you have to edit a config file because the Redshift GUI doesn't have a config editor.

**Comment by jamesray1** [comment]
I posted a comment [here](https://forum.justgetflux.com/post/15082).

**Comment by cdubz** [comment]
I have been using [my own modified version](https://github.com/cdubz/xflux-gui) successfully for a while. It seems that the `-nofork` argument is vital to getting xflux12 working. Feel free to try it our but YMMV :feelsgood:

**Comment by jamesray1** [comment]
Unfortunately it didn't work. I followed these instructions:

https://github.com/cdubz/xflux-gui#install-instructions
https://github.com/cdubz/xflux-gui#ubuntudebian-manual-install

**Comment by Peel40** [comment]
Same problem here.

**Comment by griimnak** [comment]
issue is still around
```sh
lsb_release -a && uname -a

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
Linux revenge 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jamesray1** [comment]
After I updated to Ubuntu 17.10 with GNOME built-in support for red-light filtering at night, there is no need for f.lux!

**Comment by griimnak** [comment]
@jamesray1 oh yeah, i forgot about that

**Comment by EmmanuelMess** [comment]
With xflux12 the error is:
```
$ ./xflux12 -l 0 -g 0 -k 3400 -nofork
--------
Welcome to xflux (f.lux for X)
This will only work if you're running X on console.

Found 1 screen.
Display 1 has 0 size
Sorry, we only support 8, 10, 11, and 12-bit displays right now.
```
GPU and kernel info:
```
$ sudo lshw -C display
  *-display               
       descripción: VGA compatible controller
       producto: Sky Lake Integrated Graphics
       fabricante: Intel Corporation
       id físico: 2
       información del bus: pci@0000:00:02.0
       versión: 06
       anchura: 64 bits
       reloj: 33MHz
       capacidades: pciexpress msi pm vga_controller bus_master cap_list rom
       configuración: driver=i915 latency=0
       recursos: irq:123 memoria:de000000-deffffff memoria:c0000000-cfffffff ioport:f000(size=64) memoria:c0000-dffff

```
```
$ lsb_release -a && uname -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
Linux xxxx-PC 4.14.16-041416-generic #201801310931 SMP Wed Jan 31 14:33:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jamesray1** [comment]
Just use Artful with Gnome, it has a built-in night light. xflux just doesn't seem to work.

**Comment by jamesray1** [comment]
Or read the top of this thread.

**Comment by EmmanuelMess** [comment]
I switched to Redshift and reported error here and in xflux forums.

**Comment by 0cjs** [comment]
For what it's worth, I'm using Debian 9 on an Intel Celeron N3350 (Apollo Lake) with the integrated graphics hardware (HD Graphics 500) and have the same "Sorry, we only support 8 and 10-bit displays right now." problem. Redshift works fine.

Further, <https://forum.justgetflux.com/> has been returning "503 Service Temporarily Unavailable (nginx)" for a couple of days now.

**Comment by JoshuaPettus** [comment]
In case you are one of the lucky few where xflux12 works and want to get it working with the fluxgui for the time being till a better solution comes out.  Here is a quick little hack. Simply save the xflux12 to /usr/local/bin then create a bash script at /usr/local/xflux.

Put in the following
```
#! /bin/bash
xflux12 -r 0 $@
```
That way when the fluxgui calls upon xflux, it will launch xflux12 with the -r 0 flag and append whatever else arguments at the end.

**Comment by 0cjs** [comment]
To ensure the parameters are preserved exactly, you should have double quotes around the `$@`:

    xflux12 -r 0 "$@"

**Comment by JoshuaPettus** [comment]
I suppose as good practice, especially when there could be a space as so is often the case when a directory could be an argument.
 But in this case it doesn't actually make a difference.  
I double checked with ps

**Comment by 0cjs** [comment]
I'm willing to believe that it doesn't make a difference here in most, perhaps all cases. But it's faster just to add the quotes than it is even to start thinking about if there's a case that might become a problem. (Actually showing with confidence that there are no cases where the lack of quotes could do harm is a much harder task yet.)

**Comment by AFulgens** [comment]
Just to keep the reports flowing in:
Xubuntu 16.04.5 LTS over 4.15.0-39-generic with Nvidia GTX1050 TI 4GB GDDR5 passiv (or as reported by lspci: `VGA compatible controller: NVIDIA Corporation Device 1c82 (rev a1) (prog
-if 00 [VGA controller])`) also suffers from this issue.

redshift works out-of-the-box.

**Comment by anuliuotas** [comment]
Kubuntu 19. Issue is still not fixed.

**Comment by bouwew** [comment]
LMDE 4, Nvidia 1050, not working.

**Comment by dbzlotrfan** [comment]
Using Linux Mint 19.3 (with an Nvidia GPU) with kernel 5.3.0-46, I just want th GUI to work again. . . . . . .

**Comment by dandv** [comment]
That f.lux forum thread has a post from June 2020 reporting that [xflux12 worked](https://forum.justgetflux.com/topic/2373/sorry-we-only-support-8-and-10-bit-displays-right-now/61) on Ubuntu 18.

**Comment by JoshuaPettus** [comment]
It's been working fine for me in Ubuntu Mate 2004

**Comment by Sickday** [comment]
> In case you are one of the lucky few where xflux12 works, and want to get it working with the fluxgui. For the time being till a better solution comes out, here is a quick little hack. Simply save the xflux12 to /usr/local/bin then create a bash script at /usr/local/bin/xflux.
> 
> Put in the following
> 
> ```
> #! /bin/bash
> xflux12 -r 0 $@
> ```
> 
> Be sure to make both executable with "chmod a+x"
> 
> That way when the fluxgui calls upon xflux, it will launch xflux12 with the -r 0 flag and append whatever else arguments at the end.
> 
> [EDIT]
> So many mistakes...shouldn't post when so tired...

These steps worked perfectly for me with Debian Buster on XFCE. Redshfit did not work as I'm unable to install due to a missing and uninstallable `geoclue-provider` dependency. Thanks for these steps. I've been using the xflux12 binary to utilize the `fluxgui` app for a week with no problems so far.

**Comment by ntc2** [comment]
Thanks to @LaBatata101, we now support `redshift` as the backend, which should solve this issue for anyone have problems with `xflux`.

**Comment by AlexMiller101** [comment]
### Alternative Solution for Ubuntu 22.04 users

Neither redshift nor flux is currently working even when I am installing it manually. It is not changing colors of the screen.

But the alternative is that: **Ubuntu 22.04 has a night light option similar to fluxgui** in built. 

You can access it in _Settings_ > _Display_ > _Night Light_

**Comment by ntc2** [comment]
> ### Alternative Solution for Ubuntu 22.04 users
> 
> Neither redshift nor flux is currently working even when I am installing it manually. It is not changing colors of the screen.
> 
> But the alternative is that: **Ubuntu 22.04 has a night light option similar to fluxgui** in built.
> 
> You can access it in _Settings_ > _Display_ > _Night Light_

Glad to hear you found a work around, but in case anyone else is having this problem, it could be because Ubuntu 22.04 using Wayland by default, and Redshift doesn't work with Wayland. You need to switch to Xorg to use Redshift in Ubuntu 22.04.
