### ISSUE TITLE
ImportError: No module named pexpect

### ISSUE THREAD

**Issue by ChameleonScales** [xflux-gui/xflux-gui#65]
I've tried both running with :
```
python download-xflux.py
PATH=`pwd`:$PATH PYTHONPATH=`pwd`/src:$PYTHONPATH python2.7 ./fluxgui &
```
(notice I added python 2.7 because I have 3.6 set as the default)

and installing with :
```
python ./download-xflux.py
python2.7 ./setup.py install
```
then running fluxgui, but either way I got this error :
```
Traceback (most recent call last):
  File "/usr/bin/fluxgui", line 17, in <module>
    from fluxgui.fluxapp import main
  File "/usr/lib/python2.7/site-packages/fluxgui/fluxapp.py", line 3, in <module>
    from fluxgui import fluxcontroller, settings
  File "/usr/lib/python2.7/site-packages/fluxgui/fluxcontroller.py", line 1, in <module>
    from fluxgui import xfluxcontroller
  File "/usr/lib/python2.7/site-packages/fluxgui/xfluxcontroller.py", line 1, in <module>
    import pexpect
ImportError: No module named pexpect
```

**Comment by ntc2** [comment]
Looks like you need to install the Python pexpect package.

**Comment by ChameleonScales** [comment]
You're right, I have it but only for Python 3. In fact I had all the dependencies but not for python 2, so I had to install a bunch of them. Now it works, thanks !
