### ISSUE TITLE
cant install on arch

### ISSUE THREAD

**Issue by joksik** [xflux-gui/xflux-gui#67]
so i read manual install and after i git clone and "python download-xflux.py" i have this error

`sudo python setup.py install
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/fluxgui
copying src/fluxgui/__init__.py -> build/lib/fluxgui
copying src/fluxgui/exceptions.py -> build/lib/fluxgui
copying src/fluxgui/fluxapp.py -> build/lib/fluxgui
copying src/fluxgui/fluxcontroller.py -> build/lib/fluxgui
copying src/fluxgui/settings.py -> build/lib/fluxgui
copying src/fluxgui/xfluxcontroller.py -> build/lib/fluxgui
copying src/fluxgui/preferences.glade -> build/lib/fluxgui
running build_scripts
creating build/scripts-3.6
copying and adjusting fluxgui -> build/scripts-3.6
Traceback (most recent call last):
  File "/usr/lib/python3.6/tokenize.py", line 390, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 24: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    the day""",
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/install.py", line 545, in run
    self.run_command('build')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build_scripts.py", line 50, in run
    self.copy_scripts()
  File "/usr/lib/python3.6/distutils/command/build_scripts.py", line 82, in copy_scripts
    encoding, lines = tokenize.detect_encoding(f.readline)
  File "/usr/lib/python3.6/tokenize.py", line 431, in detect_encoding
    encoding = find_cookie(first)
  File "/usr/lib/python3.6/tokenize.py", line 395, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for 'xflux'
`

edit i forgot to say that on arch i install this dependencies: 
libappindicator python2-gconf glade lib32-libxxf86vm pygtk because on arch this package: 
python-appindicator python-gconf python-glade2 libxxf86vm1  python-gtk2 

does not exist but i think that it's the same dependencies only different name

edit2; ok i fix this. in manual you write this command "

> sudo python setup.py install

but on arch to install i must type 

> sudo python2 setup.py install

**Comment by ntc2** [comment]
Try using `python2`.

**Comment by carlosnewmusic** [comment]
![imagen](https://user-images.githubusercontent.com/19379457/107261923-3d126900-6a40-11eb-8dda-a6abbb9aa49e.png)
old dependencies in arch / manjaro
